import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import Center from '../components/Center';
import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  // console.log('data: ', session);
  // console.log('status: ', status);

  return (
    <div className="h-screen overflow-hidden bg-neutral-900">
      <Head>
        <title>Nxpotify!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        {/* Sidebar */}
        <Sidebar />
        {/* Center */}
        <Center />
      </main>

      <section>{/* Player */}</section>
    </div>
  );
};

export default Home;
